# Site settings
title: Camargo Portas | Portões Automaticos
description: "Fabricação e autmação de portões."
baseurl: "" # the subpath of your site, e.g. /blog
url: "camargoportas.github.io" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Camargo Portas
    hero_description: Fabricação e Automação de Portões.

# Contact form
api_token: 3dc19c3a00cb2975754900908ee5f71f

# Contact info
contact:
    phone: (11) 99690-4000
    emergency: (11) 5012-2073 
    email: atendimento@camargoportas.com.br
    address: Avenida Agua Funda 324, sala 2, <br> São Paulo - SP

# Opening hours
monday_friday: 08h00 – 18h00
saturday: 09h00 – 12h00
sunday:

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Avenida Agua Funda, 324, São Paulo, SP
    address_details: svg/min/logo.svg

# Social settings
facebook: 
twitter: 
instagram: 
youtube: 
skype: 
feed: 

# Footer
copyright: © 2016 CamargoPortas - Todos os direitos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
